version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54322:5432"
  redis:
    image: redis:alpine
    ports:
      - "63799:6379"
  web:
    build: .
    command: "gunicorn course_project.wsgi --bind=0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - CELERY_BROKER_URL=redis://redis:6379/0
      - TELEGRAM_BOT_TOKEN=7808938876:AAEadpxMVuLP8HRE--9VMFMFQUuHy0YxVEY
      - SENDGRID_USERNAME=apikey
      - SENDGRID_PASSWORD=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

    restart: always
    volumes:
      - .:/app
  migrations:
    build: .
    command: "python manage.py migrate"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    restart: "no"
    volumes:
      - .:/app
  celery:
    build: .
    command: "celery -A course_project worker -l info"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - CELERY_BROKER_URL=redis://redis:6379/0
      - TELEGRAM_BOT_TOKEN=7808938876:AAEadpxMVuLP8HRE--9VMFMFQUuHy0YxVEY
    restart: always
    volumes:
      - .:/app