# Generated by Django 5.1.2 on 2024-10-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_remove_homework_grade_homework_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='grade',
            field=models.ManyToManyField(blank=True, to='homework.grade'),
        ),
    ]
