# Generated by Django 5.1.2 on 2024-10-27 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_alter_homework_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='grade',
            new_name='grades',
        ),
    ]
