# Generated by Django 5.1.2 on 2024-10-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_rename_grade_homework_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='grades',
            field=models.ManyToManyField(blank=True, related_name='homeworks', to='homework.grade'),
        ),
    ]
