# Generated by Django 5.1.2 on 2024-10-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
