# Generated by Django 5.1.2 on 2024-10-18 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_grade'),
        ('lesson', '0003_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='homework',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homework.homework'),
        ),
    ]
