# Generated by Django 5.1.2 on 2024-11-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
