# Generated by Django 5.1.2 on 2024-11-09 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_finalized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='finalized',
        ),
    ]
